name: Run tests
on: [ pull_request ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      # Might not be necessary because uv run pytest will install dependencies
      - name: Install dependencies
        run: |
          cd backend
          uv sync

      - name: Run Tests
        run: |
          cd backend
          uv run pytest

  # TODO: Add a job to run the frontend tests
